[package]
name = "cosmwasm-storage"
version = "0.9.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "CosmWasm library with useful helpers for Storage patterns"
repository = "https://github.com/CosmWasm/cosmwasm/tree/master/packages/storage"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
circle-ci = { repository = "CosmWasm/cosmwasm", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
# This enables iterator functionality, as exposed in cosmwasm-std/iterator
iterator = ["cosmwasm-std/iterator"]

[dependencies]
# Uses the path when built locally; uses the given version from crates.io when published
cosmwasm-std = { path = "../std", version = "0.9.0" }
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
snafu = { version = "0.6.3" }
