[toolchain]
channel = "1.68.2"
components = [
  "clippy",
  "rust-analysis",
  "rustfmt",
  "rust-src",
  "cargo",
]
targets = [
  "wasm32-unknown-unknown",
  # that is the way to test that it checks and builds againt no_std target
  "thumbv7em-none-eabi"
  ]
