[package]
name = "cosmwasm-vm-derive"
version = { workspace = true }
description = "Derive macros for cosmwasm-vm. For internal use only. No stability guarantees."
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
proc-macro = true

[dependencies]
blake2 = "0.10.6"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["extra-traits", "full"] }
