[package]
name = "cosmwasm-profiler"
version = "0.16.0-rc5"
authors = ["Tomasz Kurcz <uint@lavabit.com>"]
edition = "2018"
description = "A profiling utility for compiled Cosmwasm smart contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/profiler"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
cosmwasm-vm = { path = "../vm" }
loupe = "0.1.3"
walrus = "0.19.0"
wasmer = { version = "2.0.0", default-features = false, features = ["compiler"] }
wasmer-types = "2.0.0"
wasmer-vm = "2.0.0"

[dev-dependencies]
wasmer = { version = "2.0.0", features = ["compiler"] }
