[package]
name = "cosmwasm-profiler"
version = "0.0.0"
authors = ["Tomasz Kurcz <uint@lavabit.com>"]
edition = "2021"
description = "A profiling utility for compiled Cosmwasm smart contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/profiler"
license = "Apache-2.0"
readme = "README.md"
publish = false

[dependencies]
cosmwasm-vm = { path = "../vm" }
cosmwasm-std = { path = "../std" }
loupe = "0.1.3"
walrus = "0.19.0"
wasmer = { version = "=2.2.1", default-features = false, features = ["compiler"] }
wasmer-types = "=2.2.1"
wasmer-vm = "=2.2.1"
# wasmer = { git = "https://github.com/wasmerio/wasmer", rev = "877ce1f7c44fad853c", default-features = false, features = ["compiler"] }
# wasmer-types = { git = "https://github.com/wasmerio/wasmer", rev = "877ce1f7c44fad853c" }
# wasmer-vm = { git = "https://github.com/wasmerio/wasmer", rev = "877ce1f7c44fad853c" }
hackatom = { path = "../../contracts/hackatom", default-features = false }
csv = "1.1.6"

[dev-dependencies]
wasmer = { version = "=2.2.1", features = ["compiler"] }
# wasmer = { git = "https://github.com/wasmerio/wasmer", rev = "877ce1f7c44fad853c", features = ["compiler"] }
