[package]
name = "hackatom"
version = "0.6.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = [ "cosmwasm/backtraces", "cosmwasm-vm/backtraces" ]

[dependencies]
cosmwasm = { path = "../..", version = "0.6.2" }
# To make optimized builds (cosmwasm-opt) you need to refer to external deps, not path refs outside of docker
#cosmwasm = { git = "https://github.com/confio/cosmwasm", branch = "address-newtypes" }
schemars = "0.5"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.5.0", default-features = false, features = ["rust_1_30"] }
# needed for wasm-pack build process
wasm-bindgen = "0.2.55"

[dev-dependencies]
cosmwasm-vm = { path = "../../lib/vm", version = "0.6.2" }
# To make optimized builds (cosmwasm-opt) you need to refer to external deps, not path refs outside of docker
#cosmwasm-vm = { git = "https://github.com/confio/cosmwasm", branch = "address-newtypes" }
serde_json = "1.0"
