[package]
name = "cw-schema-codegen"
authors = ["Aumetra Weisman <aumetra@confio.gmbh>"]
edition = "2021"
version.workspace = true
publish = false
build = "build.rs"

[dependencies]
anyhow = "1.0.89"
askama = { version = "0.12.1", default-features = false }
clap = { version = "4.5.18", features = ["derive"] }
cosmwasm-schema = { version = "=2.2.0-rc.1", path = "../schema" }
cw-schema = { version = "=2.2.0-rc.1", path = "../cw-schema" }
either = "1.13.0"
heck = "0.5.0"
log = "0.4.22"
mimalloc = "0.1.43"
serde_json = "1.0.128"
simple_logger = { version = "5.0.0", features = ["stderr"] }

[dev-dependencies]
arbitrary = { version = "=1.3.2", features = ["derive"] }
derive_arbitrary = "=1.3.2"
insta = "1.40.0"
rand = { version = "0.8.5", features = ["min_const_gen"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.128"
tempfile = "3.14.0"
cosmwasm-std = { version = "2.2.0-rc.1", path = "../std", default-features = false, features = [
    "std",
] }
