[package]
name = "cosmwasm-schema-derive"
version = { workspace = true }
authors = ["Tomasz Kurcz <tom@confio.gmbh>"]
description = "Derive macros for cosmwasm-schema"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"
edition = { workspace = true }
license = "Apache-2.0"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "full", "printing"] }

[lib]
proc-macro = true
