[package]
name = "cosmwasm-core"
version = { workspace = true }
description = "Components of cosmwasm-std that can be used in no_std environments"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
